version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - demo_network

networks:
  demo_network:
    driver: bridge
