spring:
  application:
    name: "spring-boot-demo"
  flyway:
    enabled: true
    locations: classpath:/db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2