spring:
  config:
    import: optional:file:.env[.properties]
  docker:
    compose:
      lifecycle-management: start_and_stop
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  sql:
    init:
      mode: always